
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Sep 14 2026 08:42:15 EDT (Sep 14 2026 12:42:15 UTC)

// Verification Directory fv/alu4 

module alu4(A, B, OP, Y);
  input [3:0] A, B;
  input [1:0] OP;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] OP;
  wire [3:0] Y;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_16;
  wire n_17, n_18, n_20, n_21, n_22, n_23, n_24;
  OAI221X1 g733__8780(.A0 (OP[1]), .A1 (n_23), .B0 (n_24), .B1 (n_1),
       .C0 (n_4), .Y (Y[3]));
  OAI221X1 g734__4296(.A0 (OP[1]), .A1 (n_22), .B0 (n_24), .B1 (n_3),
       .C0 (n_7), .Y (Y[2]));
  XNOR2X1 g735__3772(.A (n_13), .B (n_20), .Y (n_23));
  CLKINVX1 g736(.A (n_21), .Y (n_22));
  ADDFX1 g737__1474(.A (A[2]), .B (n_9), .CI (n_16), .CO (n_20), .S
       (n_21));
  OAI221X1 g738__4547(.A0 (OP[1]), .A1 (n_18), .B0 (n_24), .B1 (n_0),
       .C0 (n_10), .Y (Y[1]));
  CLKINVX1 g739(.A (n_17), .Y (n_18));
  ADDFX1 g740__9682(.A (A[1]), .B (n_5), .CI (n_6), .CO (n_16), .S
       (n_17));
  CLKINVX1 g741(.A (n_14), .Y (Y[0]));
  AOI22X1 g742__2683(.A0 (B[0]), .A1 (n_12), .B0 (A[0]), .B1 (n_11), .Y
       (n_14));
  CLKXOR2X1 g743__1309(.A (n_8), .B (A[3]), .Y (n_13));
  OAI211X1 g744__6877(.A0 (OP[1]), .A1 (A[0]), .B0 (n_24), .C0 (n_2),
       .Y (n_12));
  OAI21X1 g747__2900(.A0 (OP[1]), .A1 (B[0]), .B0 (n_24), .Y (n_11));
  NAND3X1 g748__2391(.A (B[1]), .B (A[1]), .C (OP[1]), .Y (n_10));
  CLKXOR2X1 g749__7675(.A (B[2]), .B (OP[0]), .Y (n_9));
  CLKXOR2X1 g750__7118(.A (B[3]), .B (OP[0]), .Y (n_8));
  NAND3X1 g745__8757(.A (B[2]), .B (A[2]), .C (OP[1]), .Y (n_7));
  MX2X1 g752__1786(.A (OP[0]), .B (A[0]), .S0 (B[0]), .Y (n_6));
  CLKXOR2X1 g751__5953(.A (B[1]), .B (OP[0]), .Y (n_5));
  NAND3X1 g746__5703(.A (B[3]), .B (A[3]), .C (OP[1]), .Y (n_4));
  NOR2X1 g755__7114(.A (B[2]), .B (A[2]), .Y (n_3));
  NAND2X1 g753__5266(.A (OP[1]), .B (A[0]), .Y (n_2));
  NOR2X1 g754__2250(.A (B[3]), .B (A[3]), .Y (n_1));
  NOR2X1 g756__6083(.A (B[1]), .B (A[1]), .Y (n_0));
  NAND2X1 g757__2703(.A (OP[0]), .B (OP[1]), .Y (n_24));
endmodule

